/*  
	Author Veera Swapna Raga
    date 28/12/2022
    Database Creation
*/

CREATE DATABASE KBMS_PROJECT;
USE KBMS_PROJECT;
drop table If exists order_details;
drop table If exists product;
drop table If exists user;


CREATE TABLE USER
(
  NAME VARCHAR(45) NOT NULL ,
  EMAIL VARCHAR(45) UNIQUE NOT NULL,
  PHONE_NO BIGINT ,
  ADDRESS TEXT NOT NULL,
  DATE_OF_BIRTH DATE ,
  AGE TINYINT,
  ID_PROOF VARCHAR(45) NOT NULL,
  LOGIN_ID VARCHAR(45) PRIMARY KEY ,
  PASSWORD VARCHAR(20)
);


CREATE TABLE PRODUCT
(
   PRODUCT_ID INT AUTO_INCREMENT PRIMARY KEY ,
   PRODUCT_NAME VARCHAR(45) NOT NULL,
   PRODUCT_COUNT INT,
   TOTAL_STOCK VARCHAR(45) NOT NULL,
   BEST_BEFORE DATE,
   PRICE_PER_UNIT INT NOT NULL 
);

CREATE TABLE ORDER_DETAILS
(
   ORDER_ID INT AUTO_INCREMENT PRIMARY KEY ,
   PRODUCT_NAME VARCHAR(45) ,
   QUANTITY TINYINT NOT NULL,
   TOTAL_PRICE INT NOT NULL,
   STATUS BOOLEAN DEFAULT(1),
   LOGIN_ID VARCHAR(45) NOT NULL ,
   PRODUCT_ID INT,
   fOREIGN KEY(LOGIN_ID) REFERENCES USER(LOGIN_ID),
   FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
) AUTO_INCREMENT=1000;