/*  
	Author Veera Swapna Raga
    date 28/12/2022
    Database Creation
*/
DROP DATABASE KBMS_PROJECT;

CREATE DATABASE KBMS_PROJECT;
USE KBMS_PROJECT;

DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE CUSTOMER(
CUSTOMER_NAME VARCHAR(50), 
EMAIL VARCHAR(50), 
PHONE VARCHAR(20),
ADDRESS TEXT, 
DATE_OF_BIRTH VARCHAR(30), 
AGE INT,
PASSWORD VARCHAR(15),
IDENTITY_PROOF VARCHAR(25),
PREFERRED_LOGIN_ID VARCHAR(50),
CONSTRAINT PRIMARY KEY (PREFERRED_LOGIN_ID)
);
DROP TABLE IF EXISTS PRODUCT ;
CREATE TABLE PRODUCT
(
   PRODUCT_ID INT PRIMARY KEY ,
   PRODUCT_NAME text NOT NULL,
   PRODUCT_COUNT INT,
   TOTAL_STOCK INT NOT NULL,
   THRESHOLD_LEVEL int,
   BEST_BEFORE DATE,
   PRICE_PER_UNIT DOUBLE NOT NULL,
   TYPE_OF_PRODUCT text not null
) ;

DROP TABLE IF EXISTS ORDER_DETAILS;
CREATE TABLE ORDER_DETAILS
(
   ORDER_ID INT PRIMARY KEY DEFAULT(0),
   PREFERRED_LOGIN_ID VARCHAR(50) ,
   PRODUCT_ID INT ,
   QUANTITY TINYINT NOT NULL,
   TOTAL_PRICE DOUBLE NOT NULL,
   ORDER_DATE DATE,
   STATUS VARCHAR(10),
   CANCELLATION_ID VARCHAR(10) DEFAULT(0),
   CANCELLATION_DATE DATE,
   CANCELLATION_REASON TEXT,
   FOREIGN KEY(PREFERRED_LOGIN_ID) REFERENCES Customer(PREFERRED_LOGIN_ID),
   FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
)AUTO_INCREMENT=10001;

    
    